# Generated by Django 6.0.6 on 2026-06-14 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='trainer_uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved & uploaded'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('upload_state', models.CharField(choices=[('none', 'Not uploaded'), ('uploading', 'Uploading…'), ('done', 'Uploaded to YouTube'), ('failed', 'Upload failed')], default='none', max_length=12)),
                ('youtube_id', models.CharField(blank=True, max_length=20)),
                ('error', models.TextField(blank=True, editable=False)),
                ('review_notes', models.TextField(blank=True, help_text='Shown to the trainer (e.g. why rejected).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_submissions', to='courses.batch')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson')),
                ('required_plan', models.ForeignKey(blank=True, help_text='Minimum plan to watch once published. Blank = everyone in the batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.plan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(limit_choices_to={'role__in': ['instructor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='video_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
