# Generated by Django 6.0.6 on 2026-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_share_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
