# Generated by Django 6.0.6 on 2026-06-14 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('level', models.PositiveSmallIntegerField(help_text='Access rank. 1 = lowest. Students can open content whose required level is ≤ their plan level.', unique=True)),
                ('duration_months', models.PositiveSmallIntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('badge', models.CharField(blank=True, help_text="Optional ribbon, e.g. 'MOST POPULAR' or 'ELITE'.", max_length=30)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Visually emphasise this card on the pricing page.')),
                ('accent', models.CharField(choices=[('green', 'Green'), ('dark', 'Dark'), ('gold', 'Gold')], default='green', max_length=10)),
                ('features', models.TextField(blank=True, help_text='One feature per line — shown on the pricing page.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short one-line description.', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbs/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['instructor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Batch 01'", max_length=100)),
                ('code', models.SlugField(blank=True, max_length=60, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtube_id', models.CharField(help_text='The 11-character YouTube video ID of the UNLISTED upload (the part after v= or youtu.be/), not the full URL.', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Optional, for display.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.batch')),
                ('required_plan', models.ForeignKey(blank=True, help_text='Minimum plan to watch this video. Leave blank so every student in the batch can watch it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_lessons', to='courses.plan')),
            ],
            options={
                'ordering': ['batch', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BatchEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.batch')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='courses.plan')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'batch')},
            },
        ),
    ]
