# Generated by Django 6.0.6 on 2026-06-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Local time the class starts on this day.')),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='courses.batch')),
                ('required_plan', models.ForeignKey(blank=True, help_text='Minimum plan to join classes on this day. Blank = everyone in the batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.plan')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('batch', 'weekday', 'start_time')},
            },
        ),
    ]
