# Generated by Django 6.0.6 on 2026-06-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_batchscheduleslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Trainer who conducts this batch. Leave blank to use the course instructor.', limit_choices_to={'role__in': ['instructor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
