# Generated by Django 6.0.6 on 2026-06-16 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_batch_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchscheduleslot',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, help_text='Default plans that can join classes on this day. Empty = everyone in the batch.', related_name='allowed_slots', to='courses.plan'),
        ),
        migrations.AlterField(
            model_name='batchscheduleslot',
            name='required_plan',
            field=models.ForeignKey(blank=True, help_text="Deprecated — use 'Allowed plans' instead.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.plan'),
        ),
    ]
