# Generated by Django 6.0.6 on 2026-07-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_batch_is_self_paced_payment_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchenrollment',
            name='is_provisional',
            field=models.BooleanField(default=False, help_text="Manual-UPI payment awaiting admin verification — the student can preview only the first few lessons until it's approved."),
        ),
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='upi_screenshots/'),
        ),
    ]
