# Generated by Django 6.0.6 on 2026-07-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_recordedcourse_coursepayment_section_lecture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_vpa', models.CharField(blank=True, help_text='e.g. yourname@okhdfcbank. Setting this turns on the UPI option.', max_length=100, verbose_name='UPI ID (VPA)')),
                ('upi_payee_name', models.CharField(blank=True, help_text='Name shown in the UPI app.', max_length=100)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=60)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=120)),
                ('razorpay_webhook_secret', models.CharField(blank=True, max_length=120)),
                ('preview_lessons', models.PositiveSmallIntegerField(default=2, help_text='Lectures a manual-UPI buyer can preview before admin verification.')),
            ],
            options={
                'verbose_name': 'Payment settings',
                'verbose_name_plural': 'Payment settings',
            },
        ),
    ]
