# Generated by Django 6.0.6 on 2026-07-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_paymentsettings_default_instructor_share_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=12),
        ),
    ]
