# Generated by Django 6.0.6 on 2026-06-16 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0003_populate_allowed_plans'),
        ('courses', '0005_populate_slot_allowed_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images_purged', models.BooleanField(default=False, help_text='Set once submission images are auto-deleted to save storage.')),
                ('allowed_plans', models.ManyToManyField(blank=True, related_name='hometasks', to='courses.plan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hometasks_created', to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometasks', to='classroom.liveclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('overall', models.CharField(choices=[('pending', 'Pending review'), ('correct', 'Correct'), ('wrong', 'Needs work')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text="Trainer's feedback to the student.")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.hometask')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('hometask', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homework/%Y/%m/')),
                ('verdict', models.CharField(choices=[('none', 'Not marked'), ('correct', 'Correct'), ('wrong', 'Wrong')], default='none', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homework.homeworksubmission')),
            ],
        ),
    ]
