# Generated by Django 6.0.6 on 2026-06-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live now'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('meet_link', models.URLField(blank=True, help_text='Auto-filled from Google Meet. You may also paste a link manually.')),
                ('google_event_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.batch')),
                ('required_plan', models.ForeignKey(blank=True, help_text='Minimum plan to join this class. Leave blank so every student in the batch can join.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_classes', to='courses.plan')),
            ],
            options={
                'verbose_name_plural': 'Live classes',
                'ordering': ['start_time'],
            },
        ),
    ]
