# Generated by Django 6.0.6 on 2026-06-16 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('courses', '0004_batchscheduleslot_allowed_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='allowed_plans',
            field=models.ManyToManyField(blank=True, help_text='Which plans can join this class. Leave empty = everyone in the batch.', related_name='allowed_live_classes', to='courses.plan'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='required_plan',
            field=models.ForeignKey(blank=True, help_text="Deprecated — use 'Allowed plans' instead.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_classes', to='courses.plan'),
        ),
    ]
